language: go

go:
  - 1.15.x
  - 1.14.x
  - 1.13.x
  - 1.12.x
before_script:
  - GO_FILES=$(find . -iname '*.go' -type f | grep -v /vendor/)
  - go get github.com/golang/lint/golint

script:
  - go test -v -race ./...
  - go vet ./...
  - golint -set_exit_status $(go list ./...)